# Generated by Django 4.0.5 on 2022-06-07 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0003_alter_good_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 7, 21, 9, 33, 457304)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_adress',
            field=models.CharField(default=datetime.datetime(2022, 6, 7, 21, 11, 20, 529371), max_length=512),
            preserve_default=False,
        ),
    ]
