# Generated by Django 4.0.5 on 2022-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0004_bet_created_at_order_buyer_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Ожидает отправки'), (1, 'Отправлен'), (2, 'Получен')], default='Ожидает отправки', max_length=128),
        ),
    ]
