# Generated by Django 4.0.5 on 2022-06-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0009_alter_order_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='goodcomment',
            old_name='user',
            new_name='owner',
        ),
    ]
